import type { StyleSpecification } from "maplibre-gl";

// Geographic context comes from OSM. Missing building heights use 8 m for display only.
export const cityStyle: StyleSpecification = {
  version: 8,
  glyphs: "https://tiles.openfreemap.org/fonts/{fontstack}/{range}.pbf",
  sources: {
    city: {
      type: "vector",
      url: "https://tiles.openfreemap.org/planet",
      attribution:
        '<a href="https://openfreemap.org/">OpenFreeMap</a> · <a href="https://openmaptiles.org/">OpenMapTiles</a> · © <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>',
    },
  },
  light: {
    anchor: "viewport",
    color: "#ffffff",
    intensity: 0.45,
    position: [1.4, 205, 38],
  },
  layers: [
    {
      id: "land",
      type: "background",
      paint: { "background-color": "#eaf1f5" },
    },
    {
      id: "landuse",
      type: "fill",
      source: "city",
      "source-layer": "landuse",
      paint: { "fill-color": "#e5f0eb", "fill-opacity": 0.65 },
    },
    {
      id: "parks",
      type: "fill",
      source: "city",
      "source-layer": "park",
      paint: { "fill-color": "#cde7d8", "fill-opacity": 0.8 },
    },
    {
      id: "water",
      type: "fill",
      source: "city",
      "source-layer": "water",
      paint: { "fill-color": "#2ba7d5", "fill-antialias": true },
    },
    {
      id: "water-edge",
      type: "line",
      source: "city",
      "source-layer": "water",
      paint: {
        "line-color": "#007cae",
        "line-width": 1.2,
        "line-opacity": 0.6,
      },
    },
    {
      id: "waterways",
      type: "line",
      source: "city",
      "source-layer": "waterway",
      paint: {
        "line-color": "#23a4d0",
        "line-width": ["interpolate", ["linear"], ["zoom"], 9, 0.5, 15, 3],
      },
    },
    {
      id: "road-casing",
      type: "line",
      source: "city",
      "source-layer": "transportation",
      minzoom: 10,
      paint: {
        "line-color": "#c8d8e3",
        "line-width": [
          "interpolate",
          ["linear"],
          ["zoom"],
          10,
          1,
          15,
          7,
          18,
          18,
        ],
      },
    },
    {
      id: "roads",
      type: "line",
      source: "city",
      "source-layer": "transportation",
      paint: {
        "line-color": "#ffffff",
        "line-width": [
          "interpolate",
          ["linear"],
          ["zoom"],
          8,
          0.2,
          12,
          1.4,
          15,
          5,
          18,
          15,
        ],
      },
    },
    {
      id: "building-footprints",
      type: "fill",
      source: "city",
      "source-layer": "building",
      minzoom: 12,
      paint: { "fill-color": "#d3e0e9", "fill-outline-color": "#c0d3df" },
    },
    {
      id: "city-buildings",
      type: "fill-extrusion",
      source: "city",
      "source-layer": "building",
      minzoom: 12,
      paint: {
        "fill-extrusion-color": "#f7fbff",
        "fill-extrusion-height": ["coalesce", ["get", "render_height"], 8],
        "fill-extrusion-base": ["coalesce", ["get", "render_min_height"], 0],
        "fill-extrusion-opacity": 0.93,
        "fill-extrusion-vertical-gradient": true,
      },
    },
    {
      id: "water-labels",
      type: "symbol",
      source: "city",
      "source-layer": "waterway",
      minzoom: 12,
      layout: {
        "symbol-placement": "line",
        "text-field": ["coalesce", ["get", "name:th"], ["get", "name"], ""],
        "text-font": ["Noto Sans Regular"],
        "text-size": 13,
        "text-letter-spacing": 0.02,
      },
      paint: {
        "text-color": "#005f88",
        "text-halo-color": "#ffffff",
        "text-halo-width": 2,
      },
    },
    {
      id: "place-labels",
      type: "symbol",
      source: "city",
      "source-layer": "place",
      layout: {
        "text-field": ["coalesce", ["get", "name:th"], ["get", "name"], ""],
        "text-font": ["Noto Sans Regular"],
        "text-size": ["interpolate", ["linear"], ["zoom"], 7, 11, 15, 15],
        "text-max-width": 9,
        "text-padding": 24,
      },
      paint: {
        "text-color": "#435c73",
        "text-halo-color": "#ffffff",
        "text-halo-width": 2,
      },
    },
  ],
};
